services:
  - type: web
    name: igraliste
    runtime: static
    repo: https://github.com/Milos191405/Igraliste
    buildCommand: npm install ; npm run build
    staticPublishPath: dist
    autoDeploy: false  
version: "1"


