services:
  - type: web
    name: igraliste
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js  # Ensure this points to the correct start command
    branch: main
    source:
      repo: https://github.com/Milos191405/Igraliste
      branch: main
      rootDir: / # Adjust if your server file is in a subdirectory
    publishDirectory: dist
