services:
  - type: static
    name: igraliste
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
